### PR TITLE
hardcoded blacklist of few draw.io shortcuts

### PR DESCRIPTION
**Pull request by Speedy37**
This disable:
 - formatPanel (Ctrl + * + P)
 - indent (Ctrl + Tab)

### CODE REVIEW

**Comment by Speedy37** [comment]
Temporary fix for #15

**Comment by hediet** [comment]
Does not seem to fix `Ctrl+Tab`. It is also very hacky :D I think a less hacky way would be to register a custom key handler and calling stopPropagation. This would give more precise control of what is handled in Draw.io and what in VS Code.

**Comment by Speedy37** [comment]
Another approach might be to clear some of the arrays prevent in the returned mxKeyHandler.
But then we would have to fill it with bindings from vscode.

**Comment by hediet** [comment]
I think this fix is ok for now. If someone is interested in integrating vs code commands, this needs to be thrown anyways.
For maintaining that many vs code commands for drawio, [this](https://github.com/microsoft/vscode/issues/97399) would be nice to have.

**Comment by Speedy37** [comment]
A starting point for this might be:

```

				patchProto(EditorUi, "createKeyHandler", function (old) {
					return function (...args) {
						let keyhandler = old.apply(this, args);
                                                // These are arrays of keyCode to fn
						keyhandler.normalKeys = [];
						keyhandler.shiftKeys = [];
						keyhandler.controlKeys = [];
						keyhandler.controlShiftKeys = [];
						return keyhandler;
					};
				});

                                // Disable special handling of Tab
				EditorUi.prototype.onKeyDown = () => {};
```

**Pull request merged**
