### PR TITLE
Use Memento for local storage config

### LINKED ISSUE #242: Switch to using Memento's for storage instead of settings
VSCode now has a feature for called Memento that allows extensions to store data reliably:

https://code.visualstudio.com/api/references/vscode-api#Memento

The drawio extension currently stores data in the settings instead that clutters users settings.

There's this great tutorial about how to use it here:

https://www.chrishasz.com/blog/2020/07/28/vscode-how-to-use-local-storage-api/

### PR DESCRIPTION
**Pull request by artfuldev**
Fix #242 

In this PR we try to use Memento for the storage of configuration that we don't want the users to edit - previously they used to pollute the settings/preferences of the user.

This is just a starting point to discuss certain implementations and challenge/validate some assumptions.

1. I'm using the Memento of `globalState` (as opposed to `workspaceState`) - I'm looking for inputs here as I'm not sure how we use the local storage data (is it shared across diagrams, and the like), and I'm sure I'm not the right person to make this decision. Any context here would be great. I've made the assumption based on reading the code - it looked like we need only one key with a dependency on the extension id, so I assumed it's shared across all instances of the extension.
2. Since `globalState` inside `Config` is private, I've made the memento an explicit dependency of `DiagramConfig` (we need to pass an instance to construct) instead of trying to make it accessible like `config.globalState`. There are alternatives which we can discuss. The initial implementation is based on the assumption that this makes it extensible, makes the dependencies explicit, and segregates the interfaces in the process while not removing existing abstractions.
3. The memento updates are async, while our current setter is a synchronous API - `memento.update` returns a `Thenable<void>`. This is probably the biggest thing to discuss, as I would like to understand what we want to do here. There are several approaches each with its own merit, so it would be nice to know our intended direction. I'm happy to offer suggestions. With the code as it is now, the async update is fired but we don't wait for the updates to happen before we exit the method - this _can_ cause issues, but I'm not the best person to know how this affects us.
4. I'm assuming we can just return an empty record when we don't have anything saved - if there's a default we need to setup, we can add that.

I hope this is helpful as a starting point.

### CODE REVIEW

**Comment by artfuldev** [comment]
I also used prettier to format but cut out the changes that were not relevant to my changes.

**Comment by hediet** [comment]
Thanks, looks good!

One missing thing though:
With this, the old setting value gets lost.
I suggest to add some code that migrates the old value!

**Comment by artfuldev** [comment]
hey, thank you so much for responding!

Just so I understand correctly, you mean that - the previously stored config (in the settings part) gets lost in the Memento version, right?

Do you have any proposals on how we do that? I have a few ideas but I'd like to know if you already have an approach in mind.

**Comment by artfuldev** [comment]
also, do you mind adding this to hacktoberfest?

**Comment by hediet** [comment]
> We can do this in the constructor of DiagramConfig - do you think that's okay? 

Yes.

> We will end up doing this "does old config exist" check every time - is that okay? 

Yes.

> Do we need to think about how to deprecate this etc right now?

Maybe in two years.

**Comment by artfuldev** [comment]
Thank you!

**Comment by artfuldev** [comment]
Currently there's no way to delete the old config value. Do you think you can quickly point me to something that helps? I looked at `src/vscode-utils/VsCodeSetting.ts` but wasn't able to find out.

My current approach is to have something like:

```ts
constructor(
    public readonly uri: Uri,
    private readonly config: Config,
    private readonly memento: Memento
    ) {
    const settings = new VsCodeSetting<Record<string, string>>(key, options);
    this.migrate(settings, memento);
}

migrate(settings: VsCodeSetting<Record<string, string>>, memento: Memento) {
    // check settings, migrate, delete
    ...
}
```

Will that work, or should I try something else?

**Comment by artfuldev** [comment]
Hi, I've now added some basic migration code as I've outlined above. When the migration is done, I add a timestamp in ISO format to mark that the migration was done, and this is checked to avoid re-runs.

I've tried to retain the older code for the local storage as much as possible so as not to cause confusion.

Please let me know if we need to change anything else.

Thank you for the direction and support in helping make the contribution!

**Comment by artfuldev** [comment]
The file lint fails due to "not my changes" - do I correct it in this PR?

**Comment by artfuldev** [comment]
I've made a commit to include the linter requirements even if they are unrelated to this PR to make it easier if you want to quickly merge this. If you want to isolate the changes, I can reset the last commit.

**Comment by artfuldev** [comment]
I'll do that, thanks!

**Comment by artfuldev** [comment]
I tested this by:
1. Switching to `master` branch, running `Extension` debug script (in `launch.json`)
2. Verifying the key that was added `hediet.vscode-drawio.local-strorage` in `settings.json` (it was a base64 encoded string?)
3. Switching back to my branch, running the same script, with breakpoints on the related methods.
I've validated that the migration works, settings.json key disappears after migration, and the new memento based storage provider works.

I've tried this with Extension, Extension (dev), and Extension (dev 2) scripts as I was unsure how they were different.

I found a bug where the `localStorage.get()` would return an empty object instead of `undefined`, overriding our previously migrated settings. That's been fixed with the new check `if (!saved || Object.keys(saved).length === 0)`.

Thank you so much, please let me know if there's anything else I need to do to get this merged.

**Pull request merged**
