### PR TITLE
Release 1.6.0-alpha.6 as 1.6.0

### PR DESCRIPTION
**Pull request by hediet**
Please vote with **thumbs up** if this build works as expected or **thumbs down** if you found an issue.

If you found issues, please describe them so they can be fixed!

Once this pull request receives enough thumbs up and no issues are reported, version 1.6.0-alpha.6 will be released as 1.6.0

### CODE REVIEW

**Comment by shunte88** [comment]
👍 
clean, very nice indeed

**Comment by anderskristian** [comment]
How do I install the alpha version 
I must get some filed *.vsix - still new here

**Comment by hediet** [comment]
> How do I install the alpha version

Go to the vscode marketplace and search for `Draw.io Integration - Insiders Build`.

**Comment by anderskristian** [comment]
I can see that #238 - is not solved.
Probably did not expect that
is that not just a question of adding a script that check out the correct submodules??

**Comment by anderskristian** [comment]
How comes that 1.6.6 is 39 MB but the previous 1.5.0 is 41 MB ?

My assumption is that we are missing "Shapes" ??

**Pull request merged**
