### PR TITLE
Release 1.6.4-alpha.1 as 1.6.4

### PR DESCRIPTION
**Pull request by hediet**
Please vote with **thumbs up** if this build works as expected or **thumbs down** if you found an issue.

If you found issues, please describe them so they can be fixed!

Once this pull request receives enough thumbs up and no issues are reported, version 1.6.4-alpha.1 will be released as 1.6.4

### CODE REVIEW

**Comment by melMass** [comment]
I've only been testing the insider version for a few hours but it seems to work well!
I was using the original one (non-insider I mean) for quite some time
Thanks 🙏

**Comment by hediet** [comment]
Thank you, I will release it now!

**Comment by ArquitetoMovel** [comment]
Amazing, thanks a lot guys

**Comment by hediet** [comment]
@cakasuma I'm glad you like it and thanks for your suggestions! Please create individual issues for them, so others can find them too ;)
Issues with the dark theme are known though.

**Pull request merged**
