### PR TITLE
Requires more testing: run draw.io directly

### PR DESCRIPTION
**Pull request by Speedy37**
This remove the need to run a local server and remove one iframe on the stack.
I had to do some "hacky" thing to get draw.io to behave.

Resolves: #42 
Resolves: #28

### CODE REVIEW

**Comment by Speedy37** [comment]
In the last commit I reduced the package size and installed file count by quite a lot.

**Comment by hediet** [comment]
Thank you very much for your work! I'll have a look at in soon!

**Comment by Speedy37** [comment]
I won't work on it more. I tried the package on both macOS and windows, so far no issue.

**Comment by hediet** [comment]
I haven't figured out the best way how to work on PRs that originate from a different fork. I think it would be cool if you could grant me push rights to your fork!

**Comment by hediet** [comment]
Thanks a lot for your work - looks pretty solid! At first glance, it seems to work on my machine too! 

However, sometimes I get a weird error when the debugged VS Code instance opens a drawio editor on startup:

image

Did you experience the same?

And, I would like to mention you in the readme, once this gets merged. Are you fine with that? ;) Do you have a twitter handle you want me to link?

**Comment by hediet** [comment]
I tried to stay away from a `vscode.html` approach since it makes updating draw.io possibly harder. But it makes other things much easier. What do you think? How fragile is `vscode.html`?

**Comment by Speedy37** [comment]
Looking at how they build draw.io, I'm pretty confident it will be simpler to just update it rather than working around 80% of the useless things present in index.html

**Comment by Speedy37** [comment]
You can mention me.

Yeah, I got the same issue sometimes (didn't got it in the packaged version tho).

**Comment by hediet** [comment]
> 
Yeah, I got the same issue sometimes (didn't got it in the packaged version tho).

Argh it also happens in the packaged version, but much less often...

**Comment by Speedy37** [comment]
Before the upstream fix goes to stable, you might want to change the error text in vscode.html

**Comment by Speedy37** [comment]
So you are using prettier too :)

I've added a few helper I'm used to have in my projects.

Running `yarn fmt` will now format the src dir.
And if you setup a ci, you can reject commit that's doesn't pass `yarn fmt-check`.

**Comment by Speedy37** [comment]
If you aren't happy having all that in this PR, I move the latest commit to another branch.

**Comment by hediet** [comment]
> If you aren't happy having all that in this PR, I can move the latest commit to another branch.

It's okay, thank you ;) Yeah for larger projects I also use to setup all the CI stuff. But I don't like these incredible huge configs and all the pain setting them up.

Thank you very much for the effort you put into this PR ;) I'm thinking about merging it after I tested it on linux and releasing it soon!

**Comment by hediet** [comment]
Do you have any ideas of how I can test this extension automatically? Ideally I would like to have a workflow that a CI job publishes this extension after it got tested.

**Comment by hediet** [comment]
I think it is ready to merge (I just tested it on my VM). What do you think?

**Comment by Speedy37** [comment]
Go for it :)

**Comment by hediet** [comment]
Wait, your blacklisting is causing problems (I used the previous commit for testing). Set does not have a `get` function. With `has` it does not do anything.

**Comment by Speedy37** [comment]
I rebased on upstream/master and remove the incriminating commit.

**Comment by hediet** [comment]
Thanks! Would be interesting how to ignore those action bindings though. But I think this is ideal for another PR ;)

**Pull request merged**
