### PR TITLE
Update submodule "Draw.io" to fix Mathematical typesetting exporting issue

### PR DESCRIPTION
**Pull request by keikouto2001**
Issue #180 
The version of Draw.io used in the project (v16.0.0) is causing this issue, so I updated submodule to v20.3.0.
However, I have not checked the effect on other features, so be careful about that.

### CODE REVIEW

**Comment by hediet** [comment]
Thank you! Can you add a changelog entry like this:
https://github.com/hediet/vscode-drawio/commit/ecd7fa4b951495cbfd7d3d94a8ddfde061d1e2fa

**Comment by keikouto2001** [comment]
Adds some lines to Changelog

**Comment by MichaelHopwood** [comment]
Anything blocking this merge? This would fix a lot of my docs :)

**Comment by hediet** [comment]
Sorry, working on VS Code currently takes all my time...

**Comment by MichaelHopwood** [comment]
@keikouto2001 do you know how to use this latest version in VSCode? I'm seeing the latest official release was from last March. How do we use the latest repo from master?

**Comment by keikouto2001** [comment]
@MichaelHopwood 
I prepared my environment by trial and error, so it may not be optimal.

First, make sure the following are installed:
- npm, yarn
- Git

I followed these steps:
- Clone the repository with the `--recursive` option (this step may take an hour or more)
- Run `yarn install` in the generated `vscode-drawio` folder
- Run `yarn run build` to build
- Select `Install from VSIX` in the VSCode Extensions menu and select `vscode-drawio.vsix` that you have just built (perhaps you should uninstall the old vscode-drawio)
- Check that it works correctly

*Beware of unexpected behavior as this is not an official release

**Comment by MichaelHopwood** [comment]
@keikouto2001 Thanks for your instructions. I was able to replicate it on my end and appears to be working as expected.

**Pull request merged**
